php artisan krlove:generate:model Anak --table-name=anak
php artisan krlove:generate:model Catatan --table-name=catatan
php artisan krlove:generate:model Desa --table-name=desa
php artisan krlove:generate:model Kabupaten --table-name=kabupaten
php artisan krlove:generate:model Kecamatan --table-name=kecamatan
php artisan krlove:generate:model OrangTua --table-name=ortu
php artisan krlove:generate:model Pasangan --table-name=pasangan
php artisan krlove:generate:model PemberianAsi --table-name=pemberian_asi
php artisan krlove:generate:model PemberianImunisasi --table-name=pemberian_imunisasi
php artisan krlove:generate:model PemberianVitaminA --table-name=pemberian_vit_a
php artisan krlove:generate:model Penimbangan --table-name=penimbangan
php artisan krlove:generate:model Posyandu --table-name=posyandu
php artisan krlove:generate:model RegisterBayi --table-name=register_bayi
php artisan krlove:generate:model Role --table-name=role
# php artisan krlove:generate:model User --table-name=users
